
{
  home.file = {
    ".config/ghostty/config" = {
      text = ''
# Config generated by Ghostty Config

window-theme = system
background-opacity = 0.8
background-blur-radius = 20
background = #000000
foreground = #C9C7CD
selection-background = #3B4252
selection-foreground = #C9C7CD
cursor-color = #92A2D5
cursor-text = #161617

palette = 0=#000000
palette = 1=#EA83A5
palette = 2=#90B99F
palette = 3=#E6B99D
palette = 4=#85B5BA
palette = 5=#92A2D5
palette = 6=#85B5BA
palette = 7=#C9C7CD

palette = 8=#4C566A
palette = 9=#EA83A5
palette = 10=#90B99F
palette = 11=#E6B99D
palette = 12=#85B5BA
palette = 13=#92A2D5
palette = 14=#85B5BA
palette = 15=#C9C7CD

font-family = IosevkaTerm NF
font-size = 16
window-padding-color = extend
window-step-resize = true
window-padding-balance = true


### Mac Alt Fix
macos-option-as-alt = left

keybind = alt+left=unbind
keybind = alt+right=unbind
      '';
    };
  };
}
