package trainer

// getChangeRepeatLessons returns the 15 lessons for the Change & Repeat module
func getChangeRepeatLessons() []Exercise {
	return []Exercise{
		// Lessons 1-3: d + motion (dw, de, d$, etc.)
		{
			ID:          "changerepeat_001",
			Module:      ModuleChangeRepeat,
			Level:       1,
			Type:        ExerciseLesson,
			Code:        []string{"const badVariable = 'delete me';"},
			CursorPos:   Position{Line: 0, Col: 6},
			Mission:     "Delete the word 'badVariable' using d + motion",
			Solutions:   []string{"dw", "de"},
			Optimal:     "dw",
			Hint:        "d is the delete operator - combine it with w (word) motion",
			Explanation: "The d operator deletes text. Combine with motions: dw deletes word including space, de deletes to end of word. Think: d = delete, w = word.",
			TimeoutSecs: 30,
			Points:      10,
		},
		{
			ID:          "changerepeat_002",
			Module:      ModuleChangeRepeat,
			Level:       1,
			Type:        ExerciseLesson,
			Code:        []string{"function oldName() { return 'old implementation'; }"},
			CursorPos:   Position{Line: 0, Col: 9},
			Mission:     "Delete 'oldName' - just the word, not the parenthesis",
			Solutions:   []string{"de", "dw"},
			Optimal:     "de",
			Hint:        "de deletes to the END of the word (not including next character)",
			Explanation: "de deletes from cursor to end of word. Unlike dw, it doesn't include the space/character after. Use de when you want precise word deletion.",
			TimeoutSecs: 30,
			Points:      10,
		},
		{
			ID:          "changerepeat_003",
			Module:      ModuleChangeRepeat,
			Level:       1,
			Type:        ExerciseLesson,
			Code:        []string{"const result = oldValue + ' some extra stuff to remove';"},
			CursorPos:   Position{Line: 0, Col: 15},
			Mission:     "Delete everything from cursor to end of line using d$",
			Solutions:   []string{"d$", "D"},
			Optimal:     "d$",
			Hint:        "$ moves to end of line - combine with d to delete to end",
			Explanation: "d$ deletes from cursor to end of line. The $ motion means 'end of line'. This is so common that D is a shortcut for d$ (we'll learn that soon!).",
			TimeoutSecs: 30,
			Points:      10,
		},
		// Lessons 4-5: dd - delete line, D - delete to end
		{
			ID:          "changerepeat_004",
			Module:      ModuleChangeRepeat,
			Level:       2,
			Type:        ExerciseLesson,
			Code:        []string{"const valid = true;", "const DELETE_THIS_LINE = 'garbage';", "const alsoValid = false;"},
			CursorPos:   Position{Line: 1, Col: 0},
			Mission:     "Delete the entire middle line with dd",
			Solutions:   []string{"dd"},
			Optimal:     "dd",
			Hint:        "dd = delete + delete = delete entire line",
			Explanation: "Doubling an operator (dd) makes it act on the whole line. This is a Vim convention: cc changes line, yy yanks line. dd is one of the most used commands!",
			TimeoutSecs: 30,
			Points:      15,
		},
		{
			ID:          "changerepeat_005",
			Module:      ModuleChangeRepeat,
			Level:       2,
			Type:        ExerciseLesson,
			Code:        []string{"const config = { name: 'app' /* DELETE: old comment */ };"},
			CursorPos:   Position{Line: 0, Col: 27},
			Mission:     "Delete from cursor to end of line using D (shortcut for d$)",
			Solutions:   []string{"D", "d$"},
			Optimal:     "D",
			Hint:        "D is the uppercase shortcut - deletes to end of line",
			Explanation: "D is equivalent to d$ but faster to type. Uppercase commands often do 'stronger' versions: D deletes to end, C changes to end. One key instead of two!",
			TimeoutSecs: 30,
			Points:      15,
		},
		// Lessons 6-8: c + motion (cw, ciw, c$, etc.)
		{
			ID:          "changerepeat_006",
			Module:      ModuleChangeRepeat,
			Level:       3,
			Type:        ExerciseLesson,
			Code:        []string{"const oldName = 'value';"},
			CursorPos:   Position{Line: 0, Col: 6},
			Mission:     "CHANGE 'oldName' to something new using cw (enters insert mode)",
			Solutions:   []string{"cw", "ce"},
			Optimal:     "cw",
			Hint:        "c = change (delete + enter insert mode). cw changes word.",
			Explanation: "c (change) = d (delete) + i (insert). It deletes the text AND puts you in insert mode to type replacement. cw is 'change word' - delete word, start typing!",
			TimeoutSecs: 45,
			Points:      15,
		},
		{
			ID:          "changerepeat_007",
			Module:      ModuleChangeRepeat,
			Level:       3,
			Type:        ExerciseLesson,
			Code:        []string{"function calculateTotal(items) {", "  return items.reduce((sum, item) => sum + item.price, 0);", "}"},
			CursorPos:   Position{Line: 1, Col: 28}, // 'i' of first 'item' (cols 28-31)
			Mission:     "Change the word 'item' using ciw (change inner word - works from anywhere in word!)",
			Solutions:   []string{"ciw"},
			Optimal:     "ciw",
			Hint:        "ciw = change inner word. Works even if cursor is in MIDDLE of word!",
			Explanation: "ciw (change inner word) is MAGIC! Unlike cw, you don't need to be at word start. Cursor anywhere in 'item'? ciw changes the whole word. This is a game-changer!",
			TimeoutSecs: 45,
			Points:      20,
		},
		{
			ID:          "changerepeat_008",
			Module:      ModuleChangeRepeat,
			Level:       3,
			Type:        ExerciseLesson,
			Code:        []string{"const message = 'Hello, this needs to be completely rewritten';"},
			CursorPos:   Position{Line: 0, Col: 18},
			Mission:     "Change everything from cursor to end of line using c$",
			Solutions:   []string{"c$", "C"},
			Optimal:     "c$",
			Hint:        "c$ changes from cursor to end of line (like d$ but enters insert mode)",
			Explanation: "c$ deletes to end of line and enters insert mode. Perfect for rewriting the second half of a line. Just like d$, there's a shortcut: C (coming next!).",
			TimeoutSecs: 45,
			Points:      15,
		},
		// Lessons 9-10: cc - change line, C - change to end
		{
			ID:          "changerepeat_009",
			Module:      ModuleChangeRepeat,
			Level:       4,
			Type:        ExerciseLesson,
			Code:        []string{"function oldFunction() {", "  // This entire line needs rewriting", "  return null;", "}"},
			CursorPos:   Position{Line: 1, Col: 5},
			Mission:     "Change the entire comment line using cc",
			Solutions:   []string{"cc"},
			Optimal:     "cc",
			Hint:        "cc = change entire line (like dd but enters insert mode)",
			Explanation: "cc changes the whole line regardless of cursor position. It preserves indentation! The line is cleared but you stay at proper indent level. Super useful for rewriting lines.",
			TimeoutSecs: 45,
			Points:      20,
		},
		{
			ID:          "changerepeat_010",
			Module:      ModuleChangeRepeat,
			Level:       4,
			Type:        ExerciseLesson,
			Code:        []string{"const data = fetchData() // TODO: replace this implementation"},
			CursorPos:   Position{Line: 0, Col: 21},
			Mission:     "Change from cursor to end of line using C (the shortcut)",
			Solutions:   []string{"C", "c$"},
			Optimal:     "C",
			Hint:        "C is the uppercase shortcut for c$ - changes to end of line",
			Explanation: "C is c$ in one keystroke. Pattern: D deletes to end, C changes to end. Uppercase versions are 'to end of line' shortcuts. Faster than two keys!",
			TimeoutSecs: 45,
			Points:      20,
		},
		// Lessons 11-12: x / X - delete character
		{
			ID:          "changerepeat_011",
			Module:      ModuleChangeRepeat,
			Level:       5,
			Type:        ExerciseLesson,
			Code:        []string{"const valuee = 'typo';"},
			CursorPos:   Position{Line: 0, Col: 11},
			Mission:     "Delete the extra 'e' in 'valuee' using x",
			Solutions:   []string{"x"},
			Optimal:     "x",
			Hint:        "x deletes the character under the cursor",
			Explanation: "x is the simplest delete - just the character under cursor. Think of it as a precise eraser. Quick for fixing typos! It's like hitting Delete in other editors.",
			TimeoutSecs: 30,
			Points:      10,
		},
		{
			ID:          "changerepeat_012",
			Module:      ModuleChangeRepeat,
			Level:       5,
			Type:        ExerciseLesson,
			Code:        []string{"const value = 'fixme';;"},
			CursorPos:   Position{Line: 0, Col: 23},
			Mission:     "Delete the character BEFORE cursor using X (extra semicolon)",
			Solutions:   []string{"X"},
			Optimal:     "X",
			Hint:        "X (uppercase) deletes character BEFORE cursor (like backspace)",
			Explanation: "X deletes the character BEFORE cursor (like Backspace). x = delete at cursor, X = delete before cursor. Both are quick single-character fixes!",
			TimeoutSecs: 30,
			Points:      10,
		},
		// Lessons 13-15: . - THE DOT COMMAND (repeat last change)
		{
			ID:          "changerepeat_013",
			Module:      ModuleChangeRepeat,
			Level:       6,
			Type:        ExerciseLesson,
			Code:        []string{"const bad1 = 'delete';", "const bad2 = 'delete';", "const bad3 = 'delete';"},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Delete the first line with dd (in real Vim: dd then . would delete more lines!)",
			Solutions:   []string{"dd"},
			Optimal:     "dd",
			Hint:        "dd deletes the current line. The DOT (.) in real Vim would repeat this command!",
			Explanation: "THE DOT COMMAND (.) IS VIM'S SUPERPOWER! It repeats your last change. Delete a line with dd? Press . to delete another! Change a word with cw? Press . to change the next! This trainer teaches you the base commands - in real Vim you'll chain them with dot!",
			TimeoutSecs: 60,
			Points:      25,
		},
		{
			ID:          "changerepeat_014",
			Module:      ModuleChangeRepeat,
			Level:       6,
			Type:        ExerciseLesson,
			Code:        []string{"let count = 0;", "let total = 0;", "let sum = 0;", "let avg = 0;"},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Type 'cw' to start changing 'let' to something else (. would repeat this change!)",
			Solutions:   []string{"cw"},
			Optimal:     "cw",
			Hint:        "cw = change word. After typing replacement + Esc, . repeats the ENTIRE change!",
			Explanation: "This is the DOT command's magic! cw deletes word and enters insert mode. After typing replacement + <Esc>, pressing . repeats the ENTIRE change (delete word + type replacement). One complex edit, infinite repeats!",
			TimeoutSecs: 90,
			Points:      30,
		},
		{
			ID:          "changerepeat_015",
			Module:      ModuleChangeRepeat,
			Level:       6,
			Type:        ExerciseLesson,
			Code:        []string{"function process(data) {", "  console.log(data);", "  console.log(data.name);", "  console.log(data.value);", "  return data;", "}"},
			CursorPos:   Position{Line: 1, Col: 2},
			Mission:     "Type 'dd' to delete the console.log line (then . would delete the next ones!)",
			Solutions:   []string{"dd"},
			Optimal:     "dd",
			Hint:        "After dd, the line below moves up! Just keep pressing . to delete more lines!",
			Explanation: "PRO TIP: After dd, the line below moves up! So you might not even need j - just keep pressing . ! The dot command remembers: 'delete a line'. It doesn't care which line. This is how Vim pros clean up code FAST.",
			TimeoutSecs: 60,
			Points:      30,
		},
		// Lesson 16: gn - go to next match and select it (visual)
		{
			ID:          "changerepeat_016",
			Module:      ModuleChangeRepeat,
			Level:       7,
			Type:        ExerciseLesson,
			Code:        []string{"const foo = 1;", "const foo = 2;", "const foo = 3;", "// After /foo search, gn selects next 'foo'"},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "After searching for 'foo' (/foo), use gn to select the next match",
			Solutions:   []string{"gn"},
			Optimal:     "gn",
			Hint:        "gn goes to the Next match and Visually selects it",
			Explanation: "gn is a motion that goes to the next search match AND selects it visually. After /foo, pressing gn jumps to and selects the next 'foo'. This is the foundation for the powerful cgn pattern!",
			TimeoutSecs: 45,
			Points:      25,
		},
		// Lesson 17: cgn - change next match (THE POWER MOVE)
		{
			ID:          "changerepeat_017",
			Module:      ModuleChangeRepeat,
			Level:       7,
			Type:        ExerciseLesson,
			Code:        []string{"let oldName = 1;", "let oldName = 2;", "let oldName = 3;", "console.log(oldName);"},
			CursorPos:   Position{Line: 0, Col: 4},
			Mission:     "Use cgn to change 'oldName' (assumes /oldName was searched). Type the replacement!",
			Solutions:   []string{"cgn"},
			Optimal:     "cgn",
			Hint:        "cgn = change + go to next match. It changes the next occurrence!",
			Explanation: "cgn (change-go-next) is INCREDIBLE! After searching /oldName, cgn changes the next match. Type 'newName', press <Esc>, then just press . to change the next one! It's like a smart find-and-replace that you control one at a time.",
			TimeoutSecs: 60,
			Points:      35,
		},
		// Lesson 18: dgn - delete next match
		{
			ID:          "changerepeat_018",
			Module:      ModuleChangeRepeat,
			Level:       7,
			Type:        ExerciseLesson,
			Code:        []string{"DEBUG: starting process", "normal line here", "DEBUG: checkpoint 1", "another normal line", "DEBUG: ending process"},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Use dgn to delete 'DEBUG' occurrences (assumes /DEBUG was searched)",
			Solutions:   []string{"dgn"},
			Optimal:     "dgn",
			Hint:        "dgn = delete + go to next match. Deletes the next occurrence!",
			Explanation: "dgn deletes the next search match. After /DEBUG, dgn removes 'DEBUG', then . removes the next one. Perfect for cleaning up debug statements or removing unwanted words throughout a file!",
			TimeoutSecs: 45,
			Points:      30,
		},
		// Lesson 19: The cgn workflow (complete pattern)
		{
			ID:          "changerepeat_019",
			Module:      ModuleChangeRepeat,
			Level:       8,
			Type:        ExerciseLesson,
			Code:        []string{"// The cgn workflow:", "// 1. Search: /oldWord", "// 2. Change first: cgn + type newWord + <Esc>", "// 3. Repeat: . . . (dot for each occurrence)", "// 4. Skip one: n (then . to change next)", "const oldWord = 'first';", "const oldWord = 'second';"},
			CursorPos:   Position{Line: 5, Col: 6},
			Mission:     "Start the cgn workflow by typing cgn to change this 'oldWord'",
			Solutions:   []string{"cgn"},
			Optimal:     "cgn",
			Hint:        "cgn starts the change, then . repeats it on each subsequent match",
			Explanation: "THE CGN WORKFLOW is Vim's best-kept secret for refactoring! /word → cgn → type replacement → <Esc> → . . . to change more. Use n to skip occurrences you don't want to change. It's interactive find-replace with full control!",
			TimeoutSecs: 60,
			Points:      40,
		},
		// Lesson 20: * - search word under cursor forward
		{
			ID:          "changerepeat_020",
			Module:      ModuleChangeRepeat,
			Level:       5,
			Type:        ExerciseLesson,
			Code:        []string{"const data = fetchData();", "processData(data);", "return data;"},
			CursorPos:   Position{Line: 0, Col: 6},
			Mission:     "Search for all 'data' occurrences using * (cursor is on 'data')",
			Solutions:   []string{"*"},
			Optimal:     "*",
			Hint:        "* searches forward for the word under cursor",
			Explanation: "* (star) searches forward for the WHOLE WORD under cursor. It's like typing /\\<word\\> but instant! Essential for finding all occurrences of a variable. Combine with cgn for powerful refactoring.",
			TimeoutSecs: 30,
			Points:      20,
		},
		// Lesson 21: # - search word under cursor backward
		{
			ID:          "changerepeat_021",
			Module:      ModuleChangeRepeat,
			Level:       5,
			Type:        ExerciseLesson,
			Code:        []string{"const result = calculate();", "console.log(result);", "return result;"},
			CursorPos:   Position{Line: 2, Col: 7},
			Mission:     "Search backward for 'result' using # (cursor is on 'result')",
			Solutions:   []string{"#"},
			Optimal:     "#",
			Hint:        "# searches backward for the word under cursor",
			Explanation: "# (hash) searches BACKWARD for the word under cursor. It's the reverse of *. Use * to find next occurrence, # to find previous. Together they let you jump between all instances of a variable.",
			TimeoutSecs: 30,
			Points:      20,
		},
		// Lesson 22: n - repeat last search forward
		{
			ID:          "changerepeat_022",
			Module:      ModuleChangeRepeat,
			Level:       5,
			Type:        ExerciseLesson,
			Code:        []string{"// After using * or / to search", "const item = getItem();", "updateItem(item);", "saveItem(item);"},
			CursorPos:   Position{Line: 1, Col: 6},
			Mission:     "After * on 'item', use n to jump to next occurrence",
			Solutions:   []string{"n"},
			Optimal:     "n",
			Hint:        "n repeats the last search in the same direction",
			Explanation: "n jumps to the NEXT match of your last search (from / or *). Press n repeatedly to cycle through all occurrences. This is how you navigate through search results in Vim!",
			TimeoutSecs: 30,
			Points:      15,
		},
		// Lesson 23: N - repeat last search backward
		{
			ID:          "changerepeat_023",
			Module:      ModuleChangeRepeat,
			Level:       5,
			Type:        ExerciseLesson,
			Code:        []string{"const value = 10;", "const value = 20;", "const value = 30;", "// cursor here after searching"},
			CursorPos:   Position{Line: 3, Col: 0},
			Mission:     "Go back to previous 'value' match using N",
			Solutions:   []string{"N"},
			Optimal:     "N",
			Hint:        "N repeats the last search in the OPPOSITE direction",
			Explanation: "N jumps to the PREVIOUS match (opposite of n). Overshot with n? Press N to go back. This gives you full bidirectional navigation through search results!",
			TimeoutSecs: 30,
			Points:      15,
		},
		// Lesson 24: . - the dot command (repeat last change)
		{
			ID:          "changerepeat_024",
			Module:      ModuleChangeRepeat,
			Level:       6,
			Type:        ExerciseLesson,
			Code:        []string{"// After doing dd on first line:", "delete me too", "delete me three", "keep this one"},
			CursorPos:   Position{Line: 1, Col: 0},
			Mission:     "You just did dd. Now repeat it with . (dot)",
			Solutions:   []string{"."},
			Optimal:     ".",
			Hint:        ". repeats your last change command",
			Explanation: "THE DOT COMMAND is Vim's superpower! It repeats your last change (dd, cw, ciw, x, etc). Did dd? Press . to delete another line. Did ciw? Press . to change another word the same way. Master this!",
			TimeoutSecs: 30,
			Points:      25,
		},
	}
}

// getChangeRepeatPractice converts lessons to practice exercises
func getChangeRepeatPractice() []Exercise {
	lessons := getChangeRepeatLessons()
	practices := make([]Exercise, len(lessons))

	for i, lesson := range lessons {
		practice := lesson
		practice.Type = ExercisePractice
		practice.ID = "changerepeat_p" + lesson.ID[len("changerepeat_"):]
		practice.TimeoutSecs = lesson.TimeoutSecs / 2 // Half time for practice
		practice.Points = lesson.Points + 5           // Bonus points for practice
		practice.Hint = ""                            // No hints in practice mode
		practices[i] = practice
	}

	return practices
}

// getChangeRepeatBoss returns the boss fight for the Change & Repeat module
func getChangeRepeatBoss() *BossExercise {
	return &BossExercise{
		ID:     "changerepeat_boss",
		Module: ModuleChangeRepeat,
		Name:   "The Change Master",
		Lives:  3,
		Steps: []BossStep{
			{
				Exercise: Exercise{
					ID:          "changerepeat_boss_step1",
					Module:      ModuleChangeRepeat,
					Level:       7,
					Type:        ExerciseBoss,
					Code:        []string{"// THE CHANGE MASTER'S CHALLENGE", "function badFunction() {", "  let temp1 = 'delete this';", "  let temp2 = 'delete this';", "  let temp3 = 'delete this';", "  const result = processData();", "  return result;", "}"},
					CursorPos:   Position{Line: 2, Col: 2},
					Mission:     "Delete this temp line with dd (in real Vim: dd.. deletes all 3!)",
					Solutions:   []string{"dd"},
					Optimal:     "dd",
					Hint:        "dd deletes the entire current line",
					Explanation: "After deleting a line with dd, the line below moves up to take its place. So you can often just spam . without moving!",
					TimeoutSecs: 45,
					Points:      40,
				},
				TimeLimit: 45,
			},
			{
				Exercise: Exercise{
					ID:          "changerepeat_boss_step2",
					Module:      ModuleChangeRepeat,
					Level:       7,
					Type:        ExerciseBoss,
					Code:        []string{"function transform() {", "  var oldStyle = getValue();", "  var oldStyle2 = getValue();", "  var oldStyle3 = getValue();", "  return oldStyle + oldStyle2;", "}"},
					CursorPos:   Position{Line: 1, Col: 2},
					Mission:     "Start changing 'var' with cw (in real Vim: cwconst<Esc> then j. to repeat)",
					Solutions:   []string{"cw", "ciw"},
					Optimal:     "cw",
					Hint:        "cw changes from cursor to end of word, entering insert mode",
					Explanation: "The dot command repeats the entire change operation including the text you typed. cwconst<Esc> becomes a repeatable 'change to const' action!",
					TimeoutSecs: 60,
					Points:      50,
				},
				TimeLimit: 60,
			},
			{
				Exercise: Exercise{
					ID:          "changerepeat_boss_step3",
					Module:      ModuleChangeRepeat,
					Level:       7,
					Type:        ExerciseBoss,
					Code:        []string{"function debug() {", "  const data = fetch();", "  console.log('debug1');", "  console.log('debug2');", "  console.log('debug3');", "  return data;", "}"},
					CursorPos:   Position{Line: 2, Col: 2},
					Mission:     "Delete this console.log line with dd (in real Vim: dd.. deletes all 3)",
					Solutions:   []string{"dd"},
					Optimal:     "dd",
					Hint:        "dd deletes the entire current line",
					Explanation: "Cleaning up debug statements is a perfect use case for dd + dot. After dd, the next line moves up, so just keep pressing . !",
					TimeoutSecs: 45,
					Points:      40,
				},
				TimeLimit: 45,
			},
			{
				Exercise: Exercise{
					ID:          "changerepeat_boss_step4",
					Module:      ModuleChangeRepeat,
					Level:       7,
					Type:        ExerciseBoss,
					Code:        []string{"const result = processData(input) + extraGarbage + moreJunk;"},
					CursorPos:   Position{Line: 0, Col: 33},
					Mission:     "Remove ' + extraGarbage + moreJunk' from the line using D",
					Solutions:   []string{"D", "d$"},
					Optimal:     "D",
					Hint:        "D deletes from cursor to end of line in one keystroke",
					Explanation: "D is the 'delete to end' power move. When you need to chop off the tail of a line, D is your friend. No counting, no motions, just gone!",
					TimeoutSecs: 30,
					Points:      30,
				},
				TimeLimit: 30,
			},
			{
				Exercise: Exercise{
					ID:          "changerepeat_boss_step5",
					Module:      ModuleChangeRepeat,
					Level:       7,
					Type:        ExerciseBoss,
					Code:        []string{"// TODO: DELETE THIS COMMENT", "// This one too", "function cleanCode() {", "  return 'clean';", "}"},
					CursorPos:   Position{Line: 0, Col: 0},
					Mission:     "Delete this comment line with dd (in real Vim: dd. deletes both!)",
					Solutions:   []string{"dd"},
					Optimal:     "dd",
					Hint:        "dd deletes the entire current line",
					Explanation: "The Change Master is defeated! You've mastered the art of efficient deletion and the power of the dot command. These skills will serve you well in your Vim journey!",
					TimeoutSecs: 30,
					Points:      40,
				},
				TimeLimit: 30,
			},
		},
	}
}
