package trainer

// getTextObjectsLessons returns all lessons for the TextObjects module
func getTextObjectsLessons() []Exercise {
	return []Exercise{
		// Lesson 1: iw - inner word (basic)
		{
			ID:          "textobjects_001",
			Module:      ModuleTextObjects,
			Level:       1,
			Type:        ExerciseLesson,
			Code:        []string{"const userName = 'developer';"},
			CursorPos:   Position{Line: 0, Col: 6},
			Mission:     "Use viw to visually select the word 'userName'",
			Solutions:   []string{"viw"},
			Optimal:     "viw",
			Hint:        "v enters visual mode, then iw selects inner word",
			Explanation: "Text objects like 'iw' (inner word) need an operator: v (visual), d (delete), c (change), y (yank). Here we use 'v' to SEE what iw selects. In practice, you'll use diw, ciw, yiw directly.",
			TimeoutSecs: 30,
			Points:      10,
		},
		// Lesson 2: iw - inner word (in context)
		{
			ID:          "textobjects_002",
			Module:      ModuleTextObjects,
			Level:       1,
			Type:        ExerciseLesson,
			Code:        []string{"function calculateTotal(items, taxRate) {"},
			CursorPos:   Position{Line: 0, Col: 12},
			Mission:     "Use viw to select 'calculateTotal' - cursor can be anywhere in the word!",
			Solutions:   []string{"viw"},
			Optimal:     "viw",
			Hint:        "iw selects the entire word even if cursor is in the middle",
			Explanation: "Notice how 'iw' selects the entire word 'calculateTotal' even from the middle. This is why ciw is so powerful - no need to go to word start first! Vim treats camelCase as one word.",
			TimeoutSecs: 30,
			Points:      10,
		},
		// Lesson 3: aw - a word (includes space)
		{
			ID:          "textobjects_003",
			Module:      ModuleTextObjects,
			Level:       1,
			Type:        ExerciseLesson,
			Code:        []string{"const result = value + offset;"},
			CursorPos:   Position{Line: 0, Col: 17},
			Mission:     "Use vaw to select 'value' AND its trailing space",
			Solutions:   []string{"vaw"},
			Optimal:     "vaw",
			Hint:        "aw means 'a word' - includes surrounding whitespace",
			Explanation: "'aw' (a word) includes surrounding whitespace, while 'iw' (inner word) doesn't. Use daw when deleting to avoid leftover spaces. Use diw when changing to keep spacing intact.",
			TimeoutSecs: 30,
			Points:      15,
		},
		// Lesson 4: i" - inner double quotes
		{
			ID:          "textobjects_004",
			Module:      ModuleTextObjects,
			Level:       2,
			Type:        ExerciseLesson,
			Code:        []string{`const message = "Hello, World!";`},
			CursorPos:   Position{Line: 0, Col: 20},
			Mission:     `Use vi" to select the text inside double quotes (not the quotes)`,
			Solutions:   []string{`vi"`},
			Optimal:     `vi"`,
			Hint:        `i" selects everything INSIDE the double quotes`,
			Explanation: `i" selects text inside quotes, excluding quotes themselves. ci" is perfect for changing string contents. The cursor can be anywhere inside the quotes!`,
			TimeoutSecs: 30,
			Points:      15,
		},
		// Lesson 5: a" - a double quote (includes quotes)
		{
			ID:          "textobjects_005",
			Module:      ModuleTextObjects,
			Level:       2,
			Type:        ExerciseLesson,
			Code:        []string{`console.log("Processing data...");`},
			CursorPos:   Position{Line: 0, Col: 18},
			Mission:     `Use va" to select the entire quoted string INCLUDING the quotes`,
			Solutions:   []string{`va"`},
			Optimal:     `va"`,
			Hint:        `a" selects the quotes AND everything inside them`,
			Explanation: `a" includes the quote characters. Use da" to delete entire quoted string with quotes. Use ca" to replace the whole thing including delimiters.`,
			TimeoutSecs: 30,
			Points:      15,
		},
		// Lesson 6: i' - inner single quotes
		{
			ID:          "textobjects_006",
			Module:      ModuleTextObjects,
			Level:       2,
			Type:        ExerciseLesson,
			Code:        []string{`const apiKey = 'sk-abc123xyz';`},
			CursorPos:   Position{Line: 0, Col: 20},
			Mission:     "Use vi' to select the API key inside single quotes",
			Solutions:   []string{"vi'"},
			Optimal:     "vi'",
			Hint:        "i' works just like i\" but for single quotes",
			Explanation: "i' works identically to i\" but for single-quoted strings. In JS/TS both quote styles are common. ci' changes content, di' deletes it, yi' yanks it.",
			TimeoutSecs: 30,
			Points:      15,
		},
		// Lesson 7: a' - a single quote
		{
			ID:          "textobjects_007",
			Module:      ModuleTextObjects,
			Level:       2,
			Type:        ExerciseLesson,
			Code:        []string{`import { useState } from 'react';`},
			CursorPos:   Position{Line: 0, Col: 28},
			Mission:     "Use va' to select 'react' INCLUDING the quotes",
			Solutions:   []string{"va'"},
			Optimal:     "va'",
			Hint:        "a' includes the quote characters in the selection",
			Explanation: "va' selects the quoted string with quotes. da' deletes the entire import path with quotes. Useful when replacing one library with another.",
			TimeoutSecs: 30,
			Points:      15,
		},
		// Lesson 8: i( - inner parentheses
		{
			ID:          "textobjects_008",
			Module:      ModuleTextObjects,
			Level:       3,
			Type:        ExerciseLesson,
			Code:        []string{"const sum = add(firstNum, secondNum);"},
			CursorPos:   Position{Line: 0, Col: 20},
			Mission:     "Use vi( to select the function arguments inside parentheses",
			Solutions:   []string{"vi(", "vi)", "vib"},
			Optimal:     "vi(",
			Hint:        "i( or i) or ib all select inside parentheses",
			Explanation: "i( (also i) or ib 'inner block') selects inside parentheses. ci( rewrites all arguments at once. Works even with nested parens - Vim finds the matching pair!",
			TimeoutSecs: 30,
			Points:      20,
		},
		// Lesson 9: a( - a parentheses
		{
			ID:          "textobjects_009",
			Module:      ModuleTextObjects,
			Level:       3,
			Type:        ExerciseLesson,
			Code:        []string{"const result = compute(x * y + z);"},
			CursorPos:   Position{Line: 0, Col: 25},
			Mission:     "Use va( to select the parentheses AND everything inside",
			Solutions:   []string{"va(", "va)", "vab"},
			Optimal:     "va(",
			Hint:        "a( includes the parentheses themselves",
			Explanation: "a( includes the parentheses. da( deletes the entire argument list with parens. Useful for removing function calls entirely.",
			TimeoutSecs: 30,
			Points:      20,
		},
		// Lesson 10: i{ - inner braces
		{
			ID:          "textobjects_010",
			Module:      ModuleTextObjects,
			Level:       3,
			Type:        ExerciseLesson,
			Code:        []string{"const config = { debug: true, timeout: 5000 };"},
			CursorPos:   Position{Line: 0, Col: 25},
			Mission:     "Use vi{ to select everything inside the curly braces",
			Solutions:   []string{"vi{", "vi}", "viB"},
			Optimal:     "vi{",
			Hint:        "i{ or i} or iB selects inside curly braces",
			Explanation: "i{ (also i} or iB 'inner Block') selects inside braces. Essential for objects and function bodies. ci{ rewrites object contents, di{ empties them.",
			TimeoutSecs: 30,
			Points:      20,
		},
		// Lesson 11: a{ - a braces
		{
			ID:          "textobjects_011",
			Module:      ModuleTextObjects,
			Level:       3,
			Type:        ExerciseLesson,
			Code:        []string{"const user = { name: 'John', age: 30 };"},
			CursorPos:   Position{Line: 0, Col: 20},
			Mission:     "Use va{ to select the entire object INCLUDING the braces",
			Solutions:   []string{"va{", "va}", "vaB"},
			Optimal:     "va{",
			Hint:        "a{ includes the curly braces in the selection",
			Explanation: "a{ includes the braces. da{ deletes entire object literal. Useful when replacing an object with a variable reference or different structure.",
			TimeoutSecs: 30,
			Points:      20,
		},
		// Lesson 12: i[ - inner brackets
		{
			ID:          "textobjects_012",
			Module:      ModuleTextObjects,
			Level:       4,
			Type:        ExerciseLesson,
			Code:        []string{"const numbers = [1, 2, 3, 4, 5];"},
			CursorPos:   Position{Line: 0, Col: 20},
			Mission:     "Use vi[ to select the array elements inside the brackets",
			Solutions:   []string{"vi[", "vi]"},
			Optimal:     "vi[",
			Hint:        "i[ or i] selects inside square brackets",
			Explanation: "i[ selects inside square brackets. ci[ replaces array elements, di[ empties the array keeping brackets. Perfect for array manipulation.",
			TimeoutSecs: 30,
			Points:      20,
		},
		// Lesson 13: a[ - a brackets
		{
			ID:          "textobjects_013",
			Module:      ModuleTextObjects,
			Level:       4,
			Type:        ExerciseLesson,
			Code:        []string{"const item = inventory[selectedIndex];"},
			CursorPos:   Position{Line: 0, Col: 27},
			Mission:     "Use va[ to select the bracket accessor INCLUDING brackets",
			Solutions:   []string{"va[", "va]"},
			Optimal:     "va[",
			Hint:        "a[ includes the square brackets",
			Explanation: "a[ includes brackets. da[ removes entire array accessor, turning inventory[selectedIndex] into just inventory.",
			TimeoutSecs: 30,
			Points:      20,
		},
		// Lesson 14: it - inner tag
		{
			ID:          "textobjects_014",
			Module:      ModuleTextObjects,
			Level:       5,
			Type:        ExerciseLesson,
			Code:        []string{"<button>Click me</button>"},
			CursorPos:   Position{Line: 0, Col: 12},
			Mission:     "Use vit to select 'Click me' inside the HTML tags",
			Solutions:   []string{"vit"},
			Optimal:     "vit",
			Hint:        "it selects inside XML/HTML tags",
			Explanation: "'it' (inner tag) selects content between matching HTML/XML tags. cit changes tag content. Game-changer for web dev! Works with nested tags too.",
			TimeoutSecs: 30,
			Points:      25,
		},
		// Lesson 15: at - a tag
		{
			ID:          "textobjects_015",
			Module:      ModuleTextObjects,
			Level:       5,
			Type:        ExerciseLesson,
			Code:        []string{"<div><span>Hello</span></div>"},
			CursorPos:   Position{Line: 0, Col: 12},
			Mission:     "Use vat to select the entire <span> element including tags",
			Solutions:   []string{"vat"},
			Optimal:     "vat",
			Hint:        "at selects the entire tag including opening and closing tags",
			Explanation: "'at' (a tag) selects entire element with both tags. dat deletes complete element. cat replaces it. Essential for restructuring HTML.",
			TimeoutSecs: 30,
			Points:      30,
		},
		// Lesson 16: diw - delete inner word
		{
			ID:          "textobjects_016",
			Module:      ModuleTextObjects,
			Level:       6,
			Type:        ExerciseLesson,
			Code:        []string{"const oldVariable = 'value';"},
			CursorPos:   Position{Line: 0, Col: 8},
			Mission:     "Delete 'oldVariable' using diw (cursor can be anywhere in word)",
			Solutions:   []string{"diw"},
			Optimal:     "diw",
			Hint:        "diw = delete inner word. Works from any position in the word!",
			Explanation: "diw deletes the word under cursor, no matter where in the word you are. Unlike dw which deletes from cursor to word end, diw always gets the whole word. Use daw to also delete surrounding space.",
			TimeoutSecs: 30,
			Points:      20,
		},
		// Lesson 17: daw - delete a word (with space)
		{
			ID:          "textobjects_017",
			Module:      ModuleTextObjects,
			Level:       6,
			Type:        ExerciseLesson,
			Code:        []string{"remove this word please"},
			CursorPos:   Position{Line: 0, Col: 9},
			Mission:     "Delete 'this' AND its trailing space using daw",
			Solutions:   []string{"daw"},
			Optimal:     "daw",
			Hint:        "daw = delete a word including surrounding whitespace",
			Explanation: "daw deletes word + surrounding space, leaving clean text. Use daw when removing a word entirely. Use diw when replacing (keeps spacing for the new word).",
			TimeoutSecs: 30,
			Points:      20,
		},
		// Lesson 18: ci" - change inside quotes
		{
			ID:          "textobjects_018",
			Module:      ModuleTextObjects,
			Level:       6,
			Type:        ExerciseLesson,
			Code:        []string{`const msg = "old message";`},
			CursorPos:   Position{Line: 0, Col: 15},
			Mission:     `Change the text inside quotes using ci" (enters insert mode)`,
			Solutions:   []string{`ci"`},
			Optimal:     `ci"`,
			Hint:        `ci" = change inside quotes. Deletes content and enters insert mode`,
			Explanation: `ci" is INCREDIBLY useful! It deletes everything inside quotes and drops you into insert mode to type the replacement. Works from anywhere inside the quotes. One of the most-used text object combos!`,
			TimeoutSecs: 30,
			Points:      25,
		},
		// Lesson 19: di{ - delete inside braces
		{
			ID:          "textobjects_019",
			Module:      ModuleTextObjects,
			Level:       6,
			Type:        ExerciseLesson,
			Code:        []string{"const obj = { name: 'old', age: 0 };"},
			CursorPos:   Position{Line: 0, Col: 20},
			Mission:     "Delete everything inside the braces using di{",
			Solutions:   []string{"di{", "di}", "diB"},
			Optimal:     "di{",
			Hint:        "di{ deletes content inside {} but keeps the braces",
			Explanation: "di{ empties an object/block while keeping the braces. Result: { }. Perfect for clearing object contents before rewriting. ci{ does the same but enters insert mode.",
			TimeoutSecs: 30,
			Points:      25,
		},
		// Lesson 20: yiw - yank inner word
		{
			ID:          "textobjects_020",
			Module:      ModuleTextObjects,
			Level:       6,
			Type:        ExerciseLesson,
			Code:        []string{"const importantValue = 42;"},
			CursorPos:   Position{Line: 0, Col: 10},
			Mission:     "Yank (copy) 'importantValue' using yiw",
			Solutions:   []string{"yiw"},
			Optimal:     "yiw",
			Hint:        "yiw = yank inner word. Copies the word to register",
			Explanation: "yiw copies the word under cursor to the default register. Then paste with p. No need to position at word start - yiw grabs the whole word from anywhere!",
			TimeoutSecs: 30,
			Points:      20,
		},
		// Lesson 21: yi" - yank inside quotes
		{
			ID:          "textobjects_021",
			Module:      ModuleTextObjects,
			Level:       6,
			Type:        ExerciseLesson,
			Code:        []string{`const url = "https://api.example.com";`},
			CursorPos:   Position{Line: 0, Col: 20},
			Mission:     `Yank the URL inside quotes using yi"`,
			Solutions:   []string{`yi"`},
			Optimal:     `yi"`,
			Hint:        `yi" = yank inside quotes. Copies quoted content`,
			Explanation: `yi" copies the content inside quotes without the quotes themselves. Perfect for copying string values to use elsewhere. Combine with p to paste the URL somewhere else.`,
			TimeoutSecs: 30,
			Points:      20,
		},
	}
}

// getTextObjectsPractice converts lessons into practice exercises
func getTextObjectsPractice() []Exercise {
	lessons := getTextObjectsLessons()
	practices := make([]Exercise, len(lessons))

	for i, lesson := range lessons {
		practice := lesson
		practice.ID = "textobjects_p" + lesson.ID[len("textobjects_"):]
		practice.Type = ExercisePractice
		practice.Hint = ""
		practice.TimeoutSecs = 20
		practice.Points = lesson.Points + 10
		practices[i] = practice
	}

	return practices
}

// getTextObjectsBoss returns the boss fight for TextObjects module
func getTextObjectsBoss() *BossExercise {
	return &BossExercise{
		ID:        "textobjects_boss",
		Module:    ModuleTextObjects,
		Name:      "The Text Surgeon",
		Lives:     3,
		BonusTime: 30,
		Steps: []BossStep{
			{
				TimeLimit: 6,
				Exercise: Exercise{
					ID:        "textobjects_boss_1",
					Module:    ModuleTextObjects,
					Level:     5,
					Type:      ExerciseBoss,
					Code:      []string{"const userAuthentication = validateCredentials(input);"},
					CursorPos: Position{Line: 0, Col: 10},
					Mission:   "Select 'userAuthentication' with viw",
					Solutions: []string{"viw"},
					Optimal:   "viw",
					Points:    50,
				},
			},
			{
				TimeLimit: 6,
				Exercise: Exercise{
					ID:        "textobjects_boss_2",
					Module:    ModuleTextObjects,
					Level:     5,
					Type:      ExerciseBoss,
					Code:      []string{`const endpoint = "/api/v2/users/profile";`},
					CursorPos: Position{Line: 0, Col: 25},
					Mission:   `Select the URL path inside quotes with vi"`,
					Solutions: []string{`vi"`},
					Optimal:   `vi"`,
					Points:    50,
				},
			},
			{
				TimeLimit: 6,
				Exercise: Exercise{
					ID:        "textobjects_boss_3",
					Module:    ModuleTextObjects,
					Level:     5,
					Type:      ExerciseBoss,
					Code:      []string{"const filtered = items.filter(item => item.active && item.visible);"},
					CursorPos: Position{Line: 0, Col: 45},
					Mission:   "Select inside the filter parentheses with vi(",
					Solutions: []string{"vi(", "vi)", "vib"},
					Optimal:   "vi(",
					Points:    50,
				},
			},
			{
				TimeLimit: 6,
				Exercise: Exercise{
					ID:        "textobjects_boss_4",
					Module:    ModuleTextObjects,
					Level:     5,
					Type:      ExerciseBoss,
					Code:      []string{"const settings = { theme: 'dark', fontSize: 14, autoSave: true };"},
					CursorPos: Position{Line: 0, Col: 30},
					Mission:   "Select all properties inside braces with vi{",
					Solutions: []string{"vi{", "vi}", "viB"},
					Optimal:   "vi{",
					Points:    50,
				},
			},
			{
				TimeLimit: 6,
				Exercise: Exercise{
					ID:        "textobjects_boss_5",
					Module:    ModuleTextObjects,
					Level:     5,
					Type:      ExerciseBoss,
					Code:      []string{"<section><article>Important content here</article></section>"},
					CursorPos: Position{Line: 0, Col: 25},
					Mission:   "Select entire <article> element with vat",
					Solutions: []string{"vat"},
					Optimal:   "vat",
					Points:    50,
				},
			},
		},
	}
}
