[theme]

[colors]
AlertInfo = "#A9C7EE"
AlertWarn = "#E0C27A"
AlertError = "#FF718F"
Annotation = "#C96AA2"
Base = "#1A1218"
Guidance = "#F095C8"
Important = "#FFB1DD"
Title = "#D2CBD0"
Muted = "#A78E9B"
