[theme]
name = "gentleman-cute"
parent = "default"

[colors]
AlertInfo = "#D2CBD0"
AlertWarn = "#E0C27A"
AlertError = "#FF718F"
Annotation = "#A78E9B"
Base = "#F6EFF3"
Guidance = "#D2CBD0"
Important = "#F095C8"
Title = "#FFB1DD"
Muted = "#76616B"
