
[workspace]
switch = "Option+{N}"
moveTo = "Option+Shift+{N}"
moveColumnTo = "Unassigned"
focusAnywhere = "Unassigned"
backAndForth = "Option+Tab"
next = "Control+Option+Command+Right Arrow"
previous = "Control+Option+Command+Left Arrow"
swapWithMonitorLeft = "Unassigned"
swapWithMonitorRight = "Unassigned"
swapWithMonitorUp = "Unassigned"
swapWithMonitorDown = "Unassigned"

[focus]
column = "Control+Option+Command+{N}"
windowInColumn = "Unassigned"
left = "Control+Option+H"
down = "Control+Option+J"
up = "Control+Option+K"
right = "Control+Option+L"
previous = "Option+Command+Tab"
downOrLeft = "Unassigned"
upOrRight = "Unassigned"
windowTop = "Unassigned"
windowBottom = "Unassigned"
windowDownOrTop = "Unassigned"
windowUpOrBottom = "Unassigned"
windowOrWorkspaceDown = "Unassigned"
windowOrWorkspaceUp = "Unassigned"
columnFirst = "Option+Command+Home"
columnLast = "Option+Command+End"
monitorNext = "Option+Shift+Tab"
monitorPrevious = "Unassigned"
monitorLast = "Control+Command+Grave"

[move]
columnToIndex = "Unassigned"
left = "Option+Shift+Command+Left Arrow"
down = "Option+Shift+J"
up = "Option+Shift+K"
right = "Option+Shift+Command+Right Arrow"
windowDown = "Unassigned"
windowUp = "Unassigned"
windowDownOrToWorkspaceDown = "Unassigned"
windowUpOrToWorkspaceUp = "Unassigned"
windowToWorkspaceUp = "Hyper+Up Arrow"
windowToWorkspaceDown = "Hyper+Down Arrow"
columnToWorkspaceUp = "Unassigned"
columnToWorkspaceDown = "Unassigned"
columnLeft = "Option+Shift+H"
columnRight = "Option+Shift+L"
columnToFirst = "Control+Option+Command+Home"
columnToLast = "Control+Option+Command+End"
consumeOrExpelLeft = "Unassigned"
consumeOrExpelRight = "Unassigned"
consumeIntoColumn = "Unassigned"
expelFromColumn = "Unassigned"
"windowToWorkspaceOnMonitor.1.down" = "Unassigned"
"windowToWorkspaceOnMonitor.1.left" = "Unassigned"
"windowToWorkspaceOnMonitor.1.right" = "Unassigned"
"windowToWorkspaceOnMonitor.1.up" = "Unassigned"
"windowToWorkspaceOnMonitor.2.down" = "Unassigned"
"windowToWorkspaceOnMonitor.2.left" = "Unassigned"
"windowToWorkspaceOnMonitor.2.right" = "Unassigned"
"windowToWorkspaceOnMonitor.2.up" = "Unassigned"
"windowToWorkspaceOnMonitor.3.down" = "Unassigned"
"windowToWorkspaceOnMonitor.3.left" = "Unassigned"
"windowToWorkspaceOnMonitor.3.right" = "Unassigned"
"windowToWorkspaceOnMonitor.3.up" = "Unassigned"
"windowToWorkspaceOnMonitor.4.down" = "Unassigned"
"windowToWorkspaceOnMonitor.4.left" = "Unassigned"
"windowToWorkspaceOnMonitor.4.right" = "Unassigned"
"windowToWorkspaceOnMonitor.4.up" = "Unassigned"
"windowToWorkspaceOnMonitor.5.down" = "Unassigned"
"windowToWorkspaceOnMonitor.5.left" = "Unassigned"
"windowToWorkspaceOnMonitor.5.right" = "Unassigned"
"windowToWorkspaceOnMonitor.5.up" = "Unassigned"
"windowToWorkspaceOnMonitor.6.down" = "Unassigned"
"windowToWorkspaceOnMonitor.6.left" = "Unassigned"
"windowToWorkspaceOnMonitor.6.right" = "Unassigned"
"windowToWorkspaceOnMonitor.6.up" = "Unassigned"
"windowToWorkspaceOnMonitor.7.down" = "Unassigned"
"windowToWorkspaceOnMonitor.7.left" = "Unassigned"
"windowToWorkspaceOnMonitor.7.right" = "Unassigned"
"windowToWorkspaceOnMonitor.7.up" = "Unassigned"
"windowToWorkspaceOnMonitor.8.down" = "Unassigned"
"windowToWorkspaceOnMonitor.8.left" = "Unassigned"
"windowToWorkspaceOnMonitor.8.right" = "Unassigned"
"windowToWorkspaceOnMonitor.8.up" = "Unassigned"
"windowToWorkspaceOnMonitor.9.down" = "Unassigned"
"windowToWorkspaceOnMonitor.9.left" = "Unassigned"
"windowToWorkspaceOnMonitor.9.right" = "Unassigned"
"windowToWorkspaceOnMonitor.9.up" = "Unassigned"

[layout]
toggleFullscreen = "Option+Shift+F"
toggleNativeFullscreen = "Option+Shift+Command+Return"
toggleColumnTabbed = "Option+E"
toggleColumnFullWidth = "Unassigned"
expandColumnToAvailable = "Unassigned"
cycleColumnWidthForward = "Option+Command+Period"
cycleColumnWidthBackward = "Option+Command+Comma"
cycleWindowWidthForward = "Unassigned"
cycleWindowWidthBackward = "Unassigned"
cycleWindowHeightForward = "Unassigned"
cycleWindowHeightBackward = "Unassigned"
decreaseColumnWidth = "Option+Minus"
increaseColumnWidth = "Option+Equal"
decreaseWindowWidth = "Unassigned"
increaseWindowWidth = "Unassigned"
decreaseWindowHeight = "Option+Down Arrow"
increaseWindowHeight = "Option+Up Arrow"
resetWindowHeight = "Control+Option+Command+R"
balanceSizes = "Option+Shift+B"
scrollViewportLeft = "Option+Command+Left Bracket"
scrollViewportRight = "Option+Command+Right Bracket"
toggleFocusedFloating = "Control+Option+F"
assignScratchpad = "Unassigned"
toggleScratchpad = "Unassigned"
raiseAllFloating = "Option+Shift+Command+R"
rescueOffscreen = "Control+Option+Space"

[ui]
commandPalette = "Option+Command+Space"
menuAnywhere = "Option+Command+M"
settings = "Unassigned"
toggleOverview = "Option+Command+O"
toggleWorkspaceBar = "Unassigned"
toggleFocusFollowsMouse = "Unassigned"
toggleFocusFollowsWindowToMonitor = "Unassigned"
toggleMoveMouseToFocused = "Unassigned"
toggleBordersEnabled = "Unassigned"
togglePreventSleepEnabled = "Unassigned"
toggleIPCEnabled = "Unassigned"

[debugging]
dumpRuntimeState = "Unassigned"
resetRuntimeState = "Unassigned"
restartClearingRuntimeState = "Unassigned"
toggleTraceCapture = "Control+Option+Command+T"
