
[appearance]
mode = "dark"

[borders]
enabled = true
width = 1.0

[borders.color]
alpha = 1.0
blue = 0.5260301973608223
green = 0.0
red = 1.0

[focus]
followsMouse = false
followsWindowToMonitor = false
moveMouseToFocusedWindow = true

[gaps]
size = 8.0

[gaps.outer]
bottom = 0.0
left = 0.0
right = 0.0
top = 0.0

[general]
developerModeEnabled = false
hotkeysEnabled = true
ipcEnabled = true
preventSleepEnabled = false

[gestures]
fingerCount = 3
invertDirection = true
mouseResizeModifierKey = "option"
scrollEnabled = true
scrollModifierKey = "optionShift"
scrollSensitivity = 5.0

[mouseWarp]
axis = "horizontal"
margin = 1
monitorOrder = []

[niri]
balancedColumnCount = 2
columnWidthPresets = [0.35, 0.5, 0.65, 0.95]
infiniteLoop = false
revealPartial = "default"

[statusBar]
showAppNames = false
showWorkspaceName = false
useWorkspaceId = false

[workspaceBar]
backgroundOpacity = 0.0
deduplicateAppIcons = true
enabled = true
height = 24.0
hideEmptyWorkspaces = false
labelFontSize = 12.0
notchAware = true
position = "belowMenuBar"
reserveLayoutSpace = true
showFloatingWindows = true
showLabels = true
showTraceButton = false
windowLevel = "popup"
xOffset = 0.0
yOffset = 0.0
